\c rancho;

INSERT INTO public.bovino VALUES (1, NULL, '12', '91497C1D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bovino VALUES (2, NULL, '1', '91364A1D', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO public.bovino VALUES (3, NULL, '3', 'D38E71FC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);