-- 	id_medicamento SERIAL,
-- 	tipo_medicamento medicamento_enum,
-- 	fabricante_medicamento VARCHAR(255),
-- 	quatindade INT,
-- 	unidade_medida unidade_medida_enum,
-- 	data_validade date_type,
-- 	data_registro date_type,
-- 	primary key(id_medicamento)

\c rancho;

INSERT INTO medicamento (
    nome_medicamento,
    tipo_medicamento,
    fabricante_medicamento,
    volume_medicamento,
    unidade_medida,
    data_validade,
    data_registro,
    bula
)VALUES
    ('Potenay® 50C','Vitamínico','zoetis',50,'mg','2027-07-17','2024-05-8','CAFEÍNA Estimulante. As xantinas, grupo ao qual pertence a cafeína, são substâncias capazes de estimular o sistema nervoso, produzindo certo estado de alerta de curta duração. É um estimulante do sistema nervoso central, da função cardíaca, da circulação sanguínea e da liberação de adrenalina. A cafeína aumenta a excitabilidade do córtex sensorial, o que leva a um estado de alerta mental mais eficaz, ao aumento da capacidade de realizar trabalho muscular e redução da fadigaVITAMINA B2 (RIBOFLAVINA):A riboflavina (vitamina B2) é um nutriente essencial que mantém as funções do metabolismo em condições normais, atuando como cofator nas reações enzimáticas, principalmente em sistema de transporte de elétronsvitamina B2, ajuda as células a converterem carboidrato em energia sendo essencial para o crescimento de células, produção de células vermelhas e para a saúde dos olhos e da pele. A riboflavina atua como cofator redox no metabolismo gerador de energia, sendo essencial para a formação dos eritrócitos, a neoglicogênese e na regulação das enzimas. VITAMINA B6 (PIRIDOXINA): A vitamina B6, segundo Mendonça (2010), desempenha o papel mais importante, que é o de coenzima no processo de transaminação para a síntese de aminoácidos. Por conseguinte, a piridoxina desempenha muitos papéis-chave no metabolismo – em particular no metabolismo proteico. A vitamina B6 é necessária para o funcionamento adequado de mais de sessenta enzimas e é essencial para a síntese normal do ácido nucleico e das proteínas. Participa da multiplicação de todas as células e da produção das hemácias e das células do sistema imunológico. Influencia o sistema nervoso através de seus efeitos sobre vários minerais e neurotransmissores cerebrais. VITAMINA B3 (NICOTINAMIDA): A niacina participa da formação das coenzimas NAD (nicotinamida adenina dinucleotídeo) e NADP (nicotinamida adenina dinucleotídeo fosfato), responsáveis pela transferência de elétrons e hidrogênio de enzimas participantes do metabolismo dos carboidratos, gorduras e proteínas.'),
    ('Baytril®', 'Antibióticos', 'Bayer', 100, 'mg', '2026-10-20', '2024-04-18', 'Antibiótico de amplo espectro para tratamento de infecções respiratórias e de pele em bovinos.'),
    ('Ivomec®', 'Antiparasitários', 'Bayer', 200, 'mL', '2026-11-12', '2024-01-27', 'Antiparasitário de amplo espectro para bovinos, eficaz contra vermes gastrointestinais, ácaros, piolhos e moscas.'),
    ('RaivaVac®', 'Vacinas', 'MSD', 150, 'mL', '2025-10-02', '2024-03-20', 'Vacina contra a raiva, proporcionando imunidade duradoura contra o vírus da raiva em bovinos.'),
    ('NutriVit®', 'Vitamínico', 'Ceva', 120, 'mg', '2027-02-27', '2024-02-14', 'Suplemento vitamínico e mineral para bovinos, contendo vitaminas A, D, E e minerais essenciais.'),
    ('Tetravet®', 'Antibióticos', 'Bayer', 110, 'mg', '2026-10-12', '2024-05-07', 'Antibiótico de amplo espectro contendo tetraciclina, usado para tratar infecções bacterianas em bovinos.'),
    ('Valbazen®', 'Antiparasitários', 'Zoetis', 150, 'mL', '2026-06-05', '2024-05-19', 'Antiparasitário de amplo espectro eficaz contra vermes gastrointestinais e pulmonares em bovinos.'),
    ('Leptovac®', 'Vacinas', 'Zoetis', 90, 'mL', '2025-11-26', '2024-05-16', 'Vacina contra leptospirose, proporcionando imunidade duradoura contra diferentes sorovares de Leptospira em bovinos.'),
    ('VitaBov®', 'Vitamínico', 'Agener', 110, 'mg', '2027-04-05', '2024-01-22', 'Suplemento vitamínico completo para bovinos, contendo vitaminas e minerais essenciais.'),
    ('Penicilina®', 'Antibióticos', 'Ceva', 130, 'mg', '2026-12-14', '2024-02-02', 'Antibiótico de amplo espectro para tratamento de infecções bacterianas em bovinos.'),
    ('Dectomax®', 'Antiparasitários', 'Zoetis', 140, 'mL', '2026-08-18', '2024-03-29', 'Antiparasitário de amplo espectro eficaz contra vermes gastrointestinais e pulmonares em bovinos.'),
    ('Bravoxin®', 'Vacinas', 'Boehringer', 130, 'mL', '2025-12-15', '2024-04-11', 'Vacina contra clostridioses em bovinos, proporcionando imunidade duradoura contra múltiplas espécies de Clostridium.'),
    ('CalciForte®', 'Vitamínico', 'MSD', 90, 'mL', '2027-01-25', '2024-02-08', 'Suplemento vitamínico de cálcio para bovinos, indicado para a prevenção e tratamento da hipocalcemia.'),
    ('Oxytet®', 'Antibióticos', 'Bayer', 150, 'mg', '2026-09-15', '2024-05-05', 'Antibiótico de amplo espectro contendo oxitetraciclina, usado para tratar infecções bacterianas em bovinos.'),
    ('Cydectin®', 'Antiparasitários', 'Zoetis', 160, 'mL', '2026-11-07', '2024-02-05', 'Antiparasitário eficaz contra vermes gastrointestinais e pulmonares em bovinos.'),
    ('Aftovac®', 'Vacinas', 'Ceva', 140, 'mL', '2025-07-25', '2024-04-20', 'Vacina contra a febre aftosa, proporcionando imunidade duradoura contra o vírus da febre aftosa em bovinos.'),
    ('VitaBooster®', 'Vitamínico', 'UCBVET', 100, 'mg', '2027-03-18', '2024-01-15', 'Suplemento vitamínico para bovinos, contendo vitaminas e minerais essenciais para o crescimento saudável e produtividade.'),
    ('Clindavet®', 'Antibióticos', 'Ceva', 120, 'mg', '2026-12-29', '2024-02-12', 'Antibiótico de amplo espectro usado para tratar infecções bacterianas em bovinos.'),
    ('Dexacort®', 'Anti-inflamatórios', 'Bayer', 140, 'mg', '2025-08-02', '2024-04-29', 'Anti-inflamatório corticosteroide para o tratamento de inflamações e reações alérgicas em bovinos.'),
    ('Albendavet®', 'Antiparasitários', 'MSD', 150, 'L', '2026-07-01', '2024-02-11', 'Antiparasitário de amplo espectro eficaz contra vermes gastrointestinais e pulmonares em bovinos.'),
    ('VibrioVac®', 'Vacinas', 'Zoetis', 100, 'mL', '2025-11-07', '2024-03-21', 'Vacina contra vibriose, proporcionando imunidade duradoura contra Campylobacter fetus em bovinos.'),
    ('Multivit Plus®', 'Vitamínico', 'Agener', 110, 'mg', '2027-04-17', '2024-01-27', 'Suplemento vitamínico completo para bovinos, contendo vitaminas e minerais essenciais.'),
    ('Tylosin®', 'Antibióticos', 'Zoetis', 130, 'mg', '2026-10-01', '2024-05-09', 'Antibiótico de amplo espectro usado para tratar infecções respiratórias e de pele em bovinos.'),
    ('Prednisolona®', 'Anti-inflamatórios', 'MSD', 140, 'mg', '2025-07-20', '2024-02-26', 'Anti-inflamatório corticosteroide para o tratamento de inflamações e reações alérgicas em bovinos.'),
    ('Ivermix®', 'Antiparasitários', 'MSD', 150, 'mL', '2026-07-18', '2024-02-28', 'Antiparasitário eficaz contra vermes gastrointestinais, pulmonares e ectoparasitas em bovinos.'),
    ('Rabdomune®', 'Vacinas', 'Zoetis', 100, 'mL', '2025-10-08', '2024-03-14', 'Vacina contra a raiva para bovinos, proporcionando imunidade duradoura contra o vírus da raiva.'),
    ('Vitacap®', 'Vitamínico', 'Ceva', 120, 'mg', '2027-05-07', '2024-02-20', 'Suplemento vitamínico e mineral para bovinos, contendo vitaminas A, D, E, e minerais essenciais.'),
    ('Florfenicol®', 'Antibióticos', 'Boehringer', 120, 'mg', '2026-09-30', '2024-01-18', 'Antibiótico de amplo espectro usado para tratar infecções respiratórias e de pele em bovinos.'),
    ('Ketofen®', 'Anti-inflamatórios', 'Ceva', 130, 'mg', '2025-09-22', '2024-04-08', 'Anti-inflamatório não esteroidal (AINE) para o alívio da dor e inflamação em bovinos.'),
    ('Levamisol®', 'Antiparasitários', 'Bayer', 150, 'L', '2026-07-12', '2024-03-02', 'Antiparasitário eficaz contra vermes gastrointestinais e pulmonares em bovinos.'),
    ('Bravoxin 10®', 'Vacinas', 'Boehringer', 100, 'mL', '2025-11-01', '2024-04-03', 'Vacina contra clostridioses em bovinos, proporcionando imunidade duradoura contra múltiplas espécies de Clostridium.'),
    ('VitaGold®', 'Vitamínico', 'Agener', 110, 'mg', '2027-04-30', '2024-02-25', 'Suplemento vitamínico completo para bovinos, contendo vitaminas e minerais essenciais.');
    